"""Static pool of 100 customers shared by order generation scripts."""

CUSTOMERS = [
    {"email": "james.smith12@gmail.com", "name": "James Smith", "address": "142 Main St", "city": "Los Angeles", "state": "CA", "zip": "90012"},
    {"email": "mary.johnson88@yahoo.com", "name": "Mary Johnson", "address": "2571 Oak Ave", "city": "New York", "state": "NY", "zip": "10001"},
    {"email": "robert.williams45@outlook.com", "name": "Robert Williams", "address": "893 Elm St", "city": "Houston", "state": "TX", "zip": "77002"},
    {"email": "patricia.brown67@gmail.com", "name": "Patricia Brown", "address": "1204 Maple Dr", "city": "Miami", "state": "FL", "zip": "33101"},
    {"email": "john.jones23@hotmail.com", "name": "John Jones", "address": "3350 Cedar Ln", "city": "Chicago", "state": "IL", "zip": "60601"},
    {"email": "jennifer.garcia99@gmail.com", "name": "Jennifer Garcia", "address": "456 Pine Rd", "city": "Seattle", "state": "WA", "zip": "98101"},
    {"email": "michael.miller31@yahoo.com", "name": "Michael Miller", "address": "7821 Broadway", "city": "Boston", "state": "MA", "zip": "02101"},
    {"email": "linda.davis56@outlook.com", "name": "Linda Davis", "address": "1930 Market St", "city": "Denver", "state": "CO", "zip": "80201"},
    {"email": "david.martinez78@gmail.com", "name": "David Martinez", "address": "605 Park Ave", "city": "Portland", "state": "OR", "zip": "97201"},
    {"email": "elizabeth.anderson14@icloud.com", "name": "Elizabeth Anderson", "address": "3412 Lake Blvd", "city": "Philadelphia", "state": "PA", "zip": "19101"},
    {"email": "sarah.taylor42@gmail.com", "name": "Sarah Taylor", "address": "2205 River Rd", "city": "San Francisco", "state": "CA", "zip": "94102"},
    {"email": "william.thomas63@yahoo.com", "name": "William Thomas", "address": "871 Hill St", "city": "Buffalo", "state": "NY", "zip": "14201"},
    {"email": "karen.moore29@outlook.com", "name": "Karen Moore", "address": "4490 Sunset Blvd", "city": "Dallas", "state": "TX", "zip": "75201"},
    {"email": "richard.jackson85@gmail.com", "name": "Richard Jackson", "address": "1123 First Ave", "city": "Orlando", "state": "FL", "zip": "32801"},
    {"email": "susan.white17@hotmail.com", "name": "Susan White", "address": "6654 Second St", "city": "Springfield", "state": "IL", "zip": "62701"},
    {"email": "thomas.harris50@gmail.com", "name": "Thomas Harris", "address": "339 Main St", "city": "Tacoma", "state": "WA", "zip": "98401"},
    {"email": "margaret.martin73@yahoo.com", "name": "Margaret Martin", "address": "2087 Oak Ave", "city": "Cambridge", "state": "MA", "zip": "02139"},
    {"email": "charles.lee41@icloud.com", "name": "Charles Lee", "address": "5501 Elm St", "city": "Boulder", "state": "CO", "zip": "80301"},
    {"email": "jessica.clark96@gmail.com", "name": "Jessica Clark", "address": "1742 Maple Dr", "city": "Eugene", "state": "OR", "zip": "97401"},
    {"email": "daniel.lewis28@outlook.com", "name": "Daniel Lewis", "address": "923 Cedar Ln", "city": "Pittsburgh", "state": "PA", "zip": "15201"},
    {"email": "ashley.walker64@gmail.com", "name": "Ashley Walker", "address": "4130 Pine Rd", "city": "San Diego", "state": "CA", "zip": "92101"},
    {"email": "matthew.hall37@yahoo.com", "name": "Matthew Hall", "address": "276 Broadway", "city": "Rochester", "state": "NY", "zip": "14602"},
    {"email": "amanda.allen82@hotmail.com", "name": "Amanda Allen", "address": "8145 Market St", "city": "Austin", "state": "TX", "zip": "73301"},
    {"email": "anthony.young19@gmail.com", "name": "Anthony Young", "address": "1567 Park Ave", "city": "Tampa", "state": "FL", "zip": "33601"},
    {"email": "emily.king55@icloud.com", "name": "Emily King", "address": "3298 Lake Blvd", "city": "Naperville", "state": "IL", "zip": "60540"},
    {"email": "andrew.wright70@gmail.com", "name": "Andrew Wright", "address": "741 River Rd", "city": "Spokane", "state": "WA", "zip": "99201"},
    {"email": "donna.lopez33@yahoo.com", "name": "Donna Lopez", "address": "5620 Hill St", "city": "Worcester", "state": "MA", "zip": "01601"},
    {"email": "joshua.hill48@outlook.com", "name": "Joshua Hill", "address": "2934 Sunset Blvd", "city": "Colorado Springs", "state": "CO", "zip": "80901"},
    {"email": "michelle.scott91@gmail.com", "name": "Michelle Scott", "address": "167 First Ave", "city": "Salem", "state": "OR", "zip": "97301"},
    {"email": "kenneth.green16@hotmail.com", "name": "Kenneth Green", "address": "4473 Second St", "city": "Harrisburg", "state": "PA", "zip": "17101"},
    {"email": "nancy.adams57@gmail.com", "name": "Nancy Adams", "address": "1856 Main St", "city": "Sacramento", "state": "CA", "zip": "95814"},
    {"email": "steven.baker24@yahoo.com", "name": "Steven Baker", "address": "630 Oak Ave", "city": "Albany", "state": "NY", "zip": "12201"},
    {"email": "betty.gonzalez79@icloud.com", "name": "Betty Gonzalez", "address": "3917 Elm St", "city": "San Antonio", "state": "TX", "zip": "78201"},
    {"email": "paul.nelson43@gmail.com", "name": "Paul Nelson", "address": "2248 Maple Dr", "city": "Jacksonville", "state": "FL", "zip": "32099"},
    {"email": "dorothy.carter66@outlook.com", "name": "Dorothy Carter", "address": "589 Cedar Ln", "city": "Evanston", "state": "IL", "zip": "60201"},
    {"email": "mark.mitchell38@gmail.com", "name": "Mark Mitchell", "address": "7102 Pine Rd", "city": "Bellevue", "state": "WA", "zip": "98004"},
    {"email": "sandra.perez81@yahoo.com", "name": "Sandra Perez", "address": "1435 Broadway", "city": "Salem", "state": "MA", "zip": "01970"},
    {"email": "george.roberts52@hotmail.com", "name": "George Roberts", "address": "4760 Market St", "city": "Fort Collins", "state": "CO", "zip": "80521"},
    {"email": "ruth.turner97@gmail.com", "name": "Ruth Turner", "address": "213 Park Ave", "city": "Bend", "state": "OR", "zip": "97701"},
    {"email": "edward.phillips15@icloud.com", "name": "Edward Phillips", "address": "8534 Lake Blvd", "city": "Allentown", "state": "PA", "zip": "18101"},
    {"email": "helen.campbell69@gmail.com", "name": "Helen Campbell", "address": "3021 River Rd", "city": "San Jose", "state": "CA", "zip": "95101"},
    {"email": "brian.parker34@yahoo.com", "name": "Brian Parker", "address": "6247 Hill St", "city": "Syracuse", "state": "NY", "zip": "13201"},
    {"email": "sharon.evans87@outlook.com", "name": "Sharon Evans", "address": "1598 Sunset Blvd", "city": "Fort Worth", "state": "TX", "zip": "76101"},
    {"email": "ronald.edwards22@gmail.com", "name": "Ronald Edwards", "address": "4831 First Ave", "city": "St Petersburg", "state": "FL", "zip": "33701"},
    {"email": "laura.collins58@hotmail.com", "name": "Laura Collins", "address": "726 Second St", "city": "Peoria", "state": "IL", "zip": "61601"},
    {"email": "kevin.stewart76@gmail.com", "name": "Kevin Stewart", "address": "2159 Main St", "city": "Olympia", "state": "WA", "zip": "98501"},
    {"email": "cynthia.sanchez13@yahoo.com", "name": "Cynthia Sanchez", "address": "5482 Oak Ave", "city": "Springfield", "state": "MA", "zip": "01101"},
    {"email": "jason.morris49@icloud.com", "name": "Jason Morris", "address": "3875 Elm St", "city": "Aurora", "state": "CO", "zip": "80010"},
    {"email": "angela.rogers65@gmail.com", "name": "Angela Rogers", "address": "1130 Maple Dr", "city": "Medford", "state": "OR", "zip": "97501"},
    {"email": "gary.reed30@outlook.com", "name": "Gary Reed", "address": "6793 Cedar Ln", "city": "Erie", "state": "PA", "zip": "16501"},
    {"email": "brenda.cook84@gmail.com", "name": "Brenda Cook", "address": "2456 Pine Rd", "city": "Los Angeles", "state": "CA", "zip": "90027"},
    {"email": "timothy.morgan47@yahoo.com", "name": "Timothy Morgan", "address": "819 Broadway", "city": "New York", "state": "NY", "zip": "10013"},
    {"email": "virginia.bell72@hotmail.com", "name": "Virginia Bell", "address": "4142 Market St", "city": "Houston", "state": "TX", "zip": "77005"},
    {"email": "jeffrey.murphy18@gmail.com", "name": "Jeffrey Murphy", "address": "1575 Park Ave", "city": "Miami", "state": "FL", "zip": "33130"},
    {"email": "pamela.bailey93@icloud.com", "name": "Pamela Bailey", "address": "7308 Lake Blvd", "city": "Chicago", "state": "IL", "zip": "60614"},
    {"email": "frank.rivera36@gmail.com", "name": "Frank Rivera", "address": "3641 River Rd", "city": "Seattle", "state": "WA", "zip": "98103"},
    {"email": "catherine.cooper61@yahoo.com", "name": "Catherine Cooper", "address": "990 Hill St", "city": "Boston", "state": "MA", "zip": "02108"},
    {"email": "scott.richardson54@outlook.com", "name": "Scott Richardson", "address": "5223 Sunset Blvd", "city": "Denver", "state": "CO", "zip": "80210"},
    {"email": "diana.cox89@gmail.com", "name": "Diana Cox", "address": "258 First Ave", "city": "Portland", "state": "OR", "zip": "97209"},
    {"email": "raymond.howard27@hotmail.com", "name": "Raymond Howard", "address": "4591 Second St", "city": "Philadelphia", "state": "PA", "zip": "19103"},
    {"email": "marie.ward44@gmail.com", "name": "Marie Ward", "address": "1924 Main St", "city": "San Francisco", "state": "CA", "zip": "94110"},
    {"email": "peter.torres68@yahoo.com", "name": "Peter Torres", "address": "637 Oak Ave", "city": "Buffalo", "state": "NY", "zip": "14210"},
    {"email": "janet.peterson83@icloud.com", "name": "Janet Peterson", "address": "3970 Elm St", "city": "Dallas", "state": "TX", "zip": "75205"},
    {"email": "henry.gray11@gmail.com", "name": "Henry Gray", "address": "2303 Maple Dr", "city": "Orlando", "state": "FL", "zip": "32806"},
    {"email": "ann.ramirez59@outlook.com", "name": "Ann Ramirez", "address": "596 Cedar Ln", "city": "Springfield", "state": "IL", "zip": "62704"},
    {"email": "roger.james75@gmail.com", "name": "Roger James", "address": "7129 Pine Rd", "city": "Tacoma", "state": "WA", "zip": "98405"},
    {"email": "alice.watson40@yahoo.com", "name": "Alice Watson", "address": "1462 Broadway", "city": "Cambridge", "state": "MA", "zip": "02142"},
    {"email": "larry.brooks95@hotmail.com", "name": "Larry Brooks", "address": "4795 Market St", "city": "Boulder", "state": "CO", "zip": "80304"},
    {"email": "jean.kelly26@gmail.com", "name": "Jean Kelly", "address": "230 Park Ave", "city": "Eugene", "state": "OR", "zip": "97403"},
    {"email": "carl.sanders62@icloud.com", "name": "Carl Sanders", "address": "8563 Lake Blvd", "city": "Pittsburgh", "state": "PA", "zip": "15213"},
    {"email": "teresa.price35@gmail.com", "name": "Teresa Price", "address": "3048 River Rd", "city": "San Diego", "state": "CA", "zip": "92103"},
    {"email": "gerald.bennett80@yahoo.com", "name": "Gerald Bennett", "address": "6274 Hill St", "city": "Rochester", "state": "NY", "zip": "14607"},
    {"email": "gloria.wood53@outlook.com", "name": "Gloria Wood", "address": "1607 Sunset Blvd", "city": "Austin", "state": "TX", "zip": "78703"},
    {"email": "wayne.barnes98@gmail.com", "name": "Wayne Barnes", "address": "4840 First Ave", "city": "Tampa", "state": "FL", "zip": "33606"},
    {"email": "irene.ross21@hotmail.com", "name": "Irene Ross", "address": "753 Second St", "city": "Naperville", "state": "IL", "zip": "60563"},
    {"email": "philip.henderson46@gmail.com", "name": "Philip Henderson", "address": "2186 Main St", "city": "Spokane", "state": "WA", "zip": "99205"},
    {"email": "ruby.coleman71@yahoo.com", "name": "Ruby Coleman", "address": "5519 Oak Ave", "city": "Worcester", "state": "MA", "zip": "01604"},
    {"email": "russell.jenkins39@icloud.com", "name": "Russell Jenkins", "address": "3902 Elm St", "city": "Colorado Springs", "state": "CO", "zip": "80905"},
    {"email": "carolyn.perry86@gmail.com", "name": "Carolyn Perry", "address": "1147 Maple Dr", "city": "Salem", "state": "OR", "zip": "97305"},
    {"email": "jack.powell60@outlook.com", "name": "Jack Powell", "address": "6820 Cedar Ln", "city": "Harrisburg", "state": "PA", "zip": "17104"},
    {"email": "evelyn.long14@gmail.com", "name": "Evelyn Long", "address": "2483 Pine Rd", "city": "Sacramento", "state": "CA", "zip": "95818"},
    {"email": "bruce.patterson77@yahoo.com", "name": "Bruce Patterson", "address": "846 Broadway", "city": "Albany", "state": "NY", "zip": "12205"},
    {"email": "lillian.hughes32@hotmail.com", "name": "Lillian Hughes", "address": "4169 Market St", "city": "San Antonio", "state": "TX", "zip": "78205"},
    {"email": "albert.flores58@gmail.com", "name": "Albert Flores", "address": "1592 Park Ave", "city": "Jacksonville", "state": "FL", "zip": "32204"},
    {"email": "tiffany.washington93@icloud.com", "name": "Tiffany Washington", "address": "7325 Lake Blvd", "city": "Evanston", "state": "IL", "zip": "60204"},
    {"email": "eugene.butler25@gmail.com", "name": "Eugene Butler", "address": "3668 River Rd", "city": "Bellevue", "state": "WA", "zip": "98007"},
    {"email": "rose.simmons48@yahoo.com", "name": "Rose Simmons", "address": "1017 Hill St", "city": "Salem", "state": "MA", "zip": "01973"},
    {"email": "louis.foster74@outlook.com", "name": "Louis Foster", "address": "5250 Sunset Blvd", "city": "Fort Collins", "state": "CO", "zip": "80525"},
    {"email": "martha.gonzales61@gmail.com", "name": "Martha Gonzales", "address": "285 First Ave", "city": "Bend", "state": "OR", "zip": "97703"},
    {"email": "harry.bryant39@hotmail.com", "name": "Harry Bryant", "address": "4618 Second St", "city": "Allentown", "state": "PA", "zip": "18104"},
    {"email": "joyce.alexander83@gmail.com", "name": "Joyce Alexander", "address": "1951 Main St", "city": "San Jose", "state": "CA", "zip": "95112"},
    {"email": "ralph.russell16@yahoo.com", "name": "Ralph Russell", "address": "664 Oak Ave", "city": "Syracuse", "state": "NY", "zip": "13205"},
    {"email": "norma.griffin57@icloud.com", "name": "Norma Griffin", "address": "3997 Elm St", "city": "Fort Worth", "state": "TX", "zip": "76104"},
    {"email": "roy.diaz22@gmail.com", "name": "Roy Diaz", "address": "2330 Maple Dr", "city": "St Petersburg", "state": "FL", "zip": "33705"},
    {"email": "phyllis.hayes68@outlook.com", "name": "Phyllis Hayes", "address": "623 Cedar Ln", "city": "Peoria", "state": "IL", "zip": "61604"},
    {"email": "willie.myers44@gmail.com", "name": "Willie Myers", "address": "7156 Pine Rd", "city": "Olympia", "state": "WA", "zip": "98504"},
    {"email": "mildred.ford90@yahoo.com", "name": "Mildred Ford", "address": "1489 Broadway", "city": "Springfield", "state": "MA", "zip": "01105"},
    {"email": "howard.hamilton35@hotmail.com", "name": "Howard Hamilton", "address": "4822 Market St", "city": "Aurora", "state": "CO", "zip": "80014"},
    {"email": "frances.graham79@gmail.com", "name": "Frances Graham", "address": "257 Park Ave", "city": "Medford", "state": "OR", "zip": "97504"},
]
